import http.server
import json
import os

PORT = 8000
DB_FILE = 'db.json'

def load_db():
    if not os.path.exists(DB_FILE):
        return {}
    with open(DB_FILE, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_db(data):
    with open(DB_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

class WhatsPollHandler(http.server.SimpleHTTPRequestHandler):
    def end_headers(self):
        # Disable caching for API development preview convenience
        self.send_header('Cache-Control', 'no-store, no-cache, must-revalidate')
        super().end_headers()

    def do_GET(self):
        if self.path == '/api/state':
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            db_data = load_db()
            self.wfile.write(json.dumps(db_data).encode('utf-8'))
        else:
            # Let http.server handle regular static files (HTML, CSS, JS)
            super().do_GET()

    def do_POST(self):
        content_length = int(self.headers.get('Content-Length', 0))
        post_data = self.rfile.read(content_length) if content_length > 0 else b''
        
        try:
            payload = json.loads(post_data.decode('utf-8')) if post_data else {}
        except Exception:
            payload = {}

        if self.path == '/api/poll':
            self.handle_create_poll(payload)
        elif self.path == '/api/vote':
            self.handle_submit_vote(payload)
        elif self.path == '/api/team/member':
            self.handle_add_member(payload)
        elif self.path == '/api/team/member/delete':
            self.handle_delete_member(payload)
        else:
            self.send_response(404)
            self.end_headers()

    def handle_create_poll(self, payload):
        db = load_db()
        
        question = payload.get('question', 'Untitled Poll')
        options = payload.get('options', [])
        completion_time = payload.get('time', '1 min')
        advice = payload.get('advice', 'Select your choice.')

        # Configure new active poll state
        db['currentPoll'] = {
            "title": question,
            "description": "Suggested poll generated by WhatsPoll AI helper.",
            "options": options,
            "completionTime": completion_time,
            "responsesCount": 0,
            "winningOption": "N/A",
            "confidenceAvg": "0%",
            "voteCounts": [0] * len(options)
        }

        # Clear active sandbox votes
        db['votes'] = []

        # Prepend new poll to history log
        new_history = {
            "id": int(os.urandom(4).hex(), 16), # Random ID
            "question": question,
            "choiceText": "Created by you",
            "choiceEmoji": options[0].get('emoji', '💡') if options else '💡',
            "date": "Today",
            "type": "created",
            "favorite": False,
            "responses": 0
        }
        db['history'].insert(0, new_history)

        save_db(db)
        
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({"status": "success", "state": db}).encode('utf-8'))

    def handle_submit_vote(self, payload):
        db = load_db()
        
        option_text = payload.get('optionText')
        option_emoji = payload.get('optionEmoji', '💡')
        confidence = payload.get('confidence', 80)
        reason = payload.get('reason', '')
        timestamp = payload.get('timestamp', 'Now')

        # Log vote to database list
        new_vote = {
            "optionText": option_text,
            "optionEmoji": option_emoji,
            "confidence": confidence,
            "reason": reason,
            "timestamp": timestamp
        }
        db['votes'].append(new_vote)

        # Recalculate options metrics
        poll = db['currentPoll']
        options_list = poll['options']
        
        # Initialize voteCounts index array if sizes match
        if len(poll.get('voteCounts', [])) != len(options_list):
            poll['voteCounts'] = [0] * len(options_list)

        # Base responses + sandbox responses
        base_count = 124  # Baseline response seed
        sandbox_count = len(db['votes'])
        total_responses = base_count + sandbox_count
        poll['responsesCount'] = total_responses

        # Distribute mock baseline votes on first render
        # Let's say baseline has: option 0 (79), option 1 (30), option 2 (15)
        baseline_votes = [79, 30, 15] + [0] * (len(options_list) - 3)
        
        # Recalculate tallies
        tallies = [0] * len(options_list)
        for i in range(len(options_list)):
            opt = options_list[i]
            base_votes_opt = baseline_votes[i] if i < len(baseline_votes) else 0
            sandbox_votes_opt = sum(1 for v in db['votes'] if v['optionText'] == opt['text'])
            tallies[i] = base_votes_opt + sandbox_votes_opt

        poll['voteCounts'] = tallies

        # Find leader winning option
        max_val = -1
        winning_index = 0
        for idx, val in enumerate(tallies):
            if val > max_val:
                max_val = val
                winning_index = idx

        poll['winningOption'] = options_list[winning_index]['text'] if options_list else "N/A"

        # Calculate average confidence
        # Baseline average confidence is 82%
        base_confidence_sum = 82 * base_count
        sandbox_confidence_sum = sum(v['confidence'] for v in db['votes'])
        average_confidence = round((base_confidence_sum + sandbox_confidence_sum) / total_responses)
        poll['confidenceAvg'] = f"{average_confidence}%"

        # Add to history if not exists, or update response count in history
        for h in db['history']:
            if h['question'] == poll['title']:
                h['responses'] = total_responses
                if h['type'] == 'voted':
                    h['choiceText'] = f"Voted for: {option_text}"
                    h['choiceEmoji'] = option_emoji

        save_db(db)
        
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({"status": "success", "state": db}).encode('utf-8'))

    def handle_add_member(self, payload):
        db = load_db()
        
        space = payload.get('space', 'office')
        name = payload.get('name')
        email = payload.get('email')
        role = payload.get('role', 'Member')
        permissions = payload.get('permissions', 'Vote & Create')

        if space in db['teams']:
            team = db['teams'][space]
            # Avoid duplicate emails
            if not any(m['email'] == email for m in team['members']):
                team['members'].append({
                    "name": name,
                    "email": email,
                    "role": role,
                    "permissions": permissions
                })
                team['membersCount'] = len(team['members'])
                
        save_db(db)
        
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({"status": "success", "state": db}).encode('utf-8'))

    def handle_delete_member(self, payload):
        db = load_db()
        
        space = payload.get('space', 'office')
        email = payload.get('email')

        if space in db['teams']:
            team = db['teams'][space]
            team['members'] = [m for m in team['members'] if m['email'] != email]
            team['membersCount'] = len(team['members'])

        save_db(db)
        
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({"status": "success", "state": db}).encode('utf-8'))

# Set proper MIME mappings for standard files
WhatsPollHandler.extensions_map.update({
    '.js': 'application/javascript',
    '.css': 'text/css',
    '.html': 'text/html',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.svg': 'image/svg+xml'
})

if __name__ == '__main__':
    server_address = ('', PORT)
    httpd = http.server.HTTPServer(server_address, WhatsPollHandler)
    print(f"WhatsPoll Backend running at http://localhost:{PORT}/")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
